### ISSUE TITLE
-f 参数没用

### ISSUE THREAD

**Issue by pcbean** [peanut996/CloudflareWarpSpeedTest#1]
运行 CFWarpSpeedTest.exe -f asia.txt 
报错如下：
flag provided but not defined: -f

asia.txt 内容如下：
103.22.200.0/24
103.22.201.0/24
103.22.202.0/24
.......................................

**Comment by peanut996** [comment]
emmm 指定文件定义ip的功能我给删除了， 因为warp固定只有那几个ip段

**Comment by peanut996** [comment]
已经修复了 ➡️ [v1.0.4](https://github.com/peanut996/CloudflareWarpSpeedTest/releases/tag/v1.0.4)

**Comment by calllivecn** [comment]
v1.1.1 版本使-f ip.txt 用还是没用呀。

- ip.txt
```
188.114.98.4
188.114.96.213
162.159.192.98
188.114.96.69
162.159.204.202
188.114.97.47
188.114.96.160
188.114.97.187
162.159.193.5
162.159.192.127
...
```

**Comment by peanut996** [comment]
> v1.1.1 版本使-f ip.txt 用还是没用呀。
> 
>     * ip.txt
> 
> 
> ```
> 188.114.98.4
> 188.114.96.213
> 162.159.192.98
> 188.114.96.69
> 162.159.204.202
> 188.114.97.47
> 188.114.96.160
> 188.114.97.187
> 162.159.193.5
> 162.159.192.127
> ...
> ```

`panic: runtime error: slice bounds out of range [:5000] with capacity ***` 
报错是这个吗

**Comment by peanut996** [comment]
哦哦 可以考虑优化一下
