### ISSUE TITLE
-p参数有问题

### ISSUE THREAD

**Issue by deyangyvtian** [peanut996/CloudflareWarpSpeedTest#10]
显示出来的结果是对的，但是写入csv的数目还是所有可用

**Comment by peanut996** [comment]
设计如此，你的预期是什么样的？

**Comment by 17sanbu78** [comment]
应该是，-p30结果文件里也只显示30个不然没有什么意义啊

**Comment by peanut996** [comment]
> 应该是，-p30结果文件里也只显示30个不然没有什么意义啊

意义是在限制console打印的数量，输出文件作为全量的数据备份。 拿到csv文件自己可以随便处理。
