### ISSUE TITLE
[Discussion] WARP can now connect to HKG data center, but experiencing packet loss

### ISSUE THREAD

**Issue by NKRRR** [peanut996/CloudflareWarpSpeedTest#11]
Hi, first of all, thank you for developing this project.
Based on my observations:
Although the latency has decreased quite a bit, there is a **high rate of packet** loss and **very low bandwidth**.
After testing my network environment, before the addition of the HKG Endpoint, the packet loss and latency for both IPv6 and IPv4 only increased by around 50% during certain time periods. This could possibly be due to intermittent blocking or frequent speed tests causing Cloudflare to temporarily block my IP.
Is this happening to only me, or is everyone experiencing this issue?
Are there any solutions to this problem?

**Comment by peanut996** [comment]
Hi there, it's true that there might be a brief period of unavailability immediately following a speed test, which could be related to your network environment. Factors such as the performance of your router could play a role. 

Have you tried waiting for about 5 minutes after conducting a speed test before using the service again?

**Comment by NKRRR** [comment]
Before the HKG Endpoint was added, each blocking period lasted about 2 hours, mostly occurring between 9 PM and 2 AM. I suspect that this might be due to high load on Cloudflare servers, causing them to shift services to other nodes. Also, before the HKG Endpoint was added, using XIU2/CloudflareSpeedTest 's HTTP speed test failed to measure HTTP latency and download speed. I highly suspect that this is because my frequent speed tests caused Cloudflare to intermittently block my IP.

Currently, with the HKG Endpoint, I consistently experience packet loss and only 20 Mbps bandwidth. This should not be caused by my local devices. It is possibly due to ISP QOS/blocking.

**Comment by peanut996** [comment]
Perhaps, but we primarily use it in mainland China, and we are unable to connect directly to the HKG endpoint, so we cannot provide further information.

**Comment by NKRRR** [comment]
In China, they are attempting to warp IPv6. Now, most of China can directly connect to data centers in Hong Kong (HKG)

**Comment by NKRRR** [comment]
When I use speed.cloudflare.com/cdn-cgi/trace, it shows that the endpoint is HKG.
