### ISSUE TITLE
建议添加构建`arm64`版本

### ISSUE THREAD

**Issue by thiliapr** [peanut996/CloudflareWarpSpeedTest#13]
截止至`Release v1.3.9`，发布的二进制文件没有`arm64`结构的版本，只有`amd64`结构版本。我建议构建时添加`arm64`版本。

**Comment by gazedreamily** [comment]
arm版本的构建已经在 #14 中添加

**Comment by peanut996** [comment]
已经发布1.4.0版本，包含arm64的二进制文件
