### ISSUE TITLE
使用PrivateKey时获取不到ip

### ISSUE THREAD

**Issue by f111fei** [peanut996/CloudflareWarpSpeedTest#21]
https://github.com/peanut996/CloudflareWarpSpeedTest/blob/f75f50aa2f20a43934419cb59ebbb942d3b52f23/main.go#L77

这个地方是不是应该改成 `task.PublicKey`

**Comment by peanut996** [comment]
看起来是的

**Comment by peanut996** [comment]
不过用private key是为了自定义测试wireguard，如果是用warp 服务不用改这个的

**Comment by peanut996** [comment]
Already fixed in v1.4.3

**Comment by f111fei** [comment]
另外说个题外话，我用这个工具优选出来的ipv6使用wireguard握手成功一次之后后面就一直无法握手成功，导致无法使用。不知道你那边是不是一样的情况。

wireguard windows和wireguard ios都是一样。，猜测是被墙干掉了？

![IMG_4463](https://github.com/peanut996/CloudflareWarpSpeedTest/assets/7069719/15b15d71-bfac-4b0c-ab69-b422191cca4b)
