### ISSUE TITLE
检测到的ipv4地址无法使用

### ISSUE THREAD

**Issue by donnanszex7654** [peanut996/CloudflareWarpSpeedTest#22]
如题，最近发现检测到的ipv4地址显著减少，并且检测到的地址也无法使用

**Comment by peanut996** [comment]
防火墙封锁导致，IPv4可以放弃了，尝试IPv6。

**Comment by donnanszex7654** [comment]
> 防火墙封锁导致，IPv4可以放弃了，尝试IPv6。

请问一下ipv6怎么使用啊？我发现如果添加ipv6参数，发现无法检测到有用的ip，如果使用`-ip 2606:4700::/32`也无法测试ipv6地址。是否是由于我本地环境不支持ipv6导致？

**Comment by peanut996** [comment]
大概率是。请自行探索如何检测和添加ipv6。
