### ISSUE TITLE
[讨论]安徽电信ipv6所有线路都不可用了 

### ISSUE THREAD

**Issue by latiao-1337** [peanut996/CloudflareWarpSpeedTest#26]
安徽电信ipv4 还可以有差不多10-50个可用 ipv6所有线路都不可用  尝试过手机流量热点 其他运营商没试过(手里没有)
大家情况怎么样
![图片](https://github.com/user-attachments/assets/72fd5757-a341-454d-ba0a-8672e82e79da)

备注:
自身网络正常宽带和热点均支持ipv6

**Comment by wxyzh** [comment]
江苏电信一样的IPv6不可用

**Comment by gatsby0203** [comment]
北京也不行～

**Comment by peanut996** [comment]
早点换别的工具吧。 wg协议太容易识别了

**Comment by peanut996** [comment]
哦对了 
Ipv6 的地址太多了 
我这里只选了一个子网
有兴趣的可以扫全部

**Comment by peanut996** [comment]
赶紧换其他工具吧

**Comment by typenoob** [comment]
扫出来是有的 telnet不通 是GG了吗
