### ISSUE TITLE
it cannot be installed on Mac M1 Apple chip

### ISSUE THREAD

**Issue by paul726** [peanut996/CloudflareWarpSpeedTest#3]
i encounter an issue when i tried to install it on my device(Apple M1 Max / Mac os 13.5.1 ), thank you for your contribution, if you can fix it that would be better.
and below is error info

go install github.com/peanut996/CloudflareWarpSpeedTest@latest
go: downloading github.com/peanut996/CloudflareWarpSpeedTest v1.1.2
go: downloading golang.zx2c4.com/wireguard v0.0.0-20230704135630-469159ecf7d1
go: downloading github.com/cheggaaa/pb/v3 v3.1.4
go: downloading github.com/VividCortex/ewma v1.2.0
go: downloading github.com/fatih/color v1.15.0
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.19
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading golang.org/x/sys v0.6.0
go: downloading golang.org/x/net v0.7.0
go: downloading golang.org/x/crypto v0.6.0
go: downloading gvisor.dev/gvisor v0.0.0-20221203005347-703fd9b7fbc0
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/google/btree v1.0.1
package github.com/peanut996/CloudflareWarpSpeedTest
	imports github.com/peanut996/CloudflareWarpSpeedTest/task
	imports golang.zx2c4.com/wireguard/tun/netstack
	imports gvisor.dev/gvisor/pkg/bufferv2
	imports gvisor.dev/gvisor/pkg/atomicbitops
	imports gvisor.dev/gvisor/pkg/cpuid
	imports gvisor.dev/gvisor/pkg/state
	imports gvisor.dev/gvisor/pkg/state/wire
	imports gvisor.dev/gvisor/pkg/gohacks: build constraints exclude all Go files in /Users/paul/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20221203005347-703fd9b7fbc0/pkg/gohacks`

**Comment by peanut996** [comment]
try to use go `v1.20` to compile it.
