### ISSUE TITLE
没有用的变量: `MaxWarpPortRange`

### ISSUE THREAD

**Issue by thiliapr** [peanut996/CloudflareWarpSpeedTest#30]
变量在这里：
https://github.com/peanut996/CloudflareWarpSpeedTest/blob/ef96fb55b9188a3922d8e752dab04ed5b227a146/task/warping.go#L82
这个变量找遍整个仓库都没有使用过，是不是放弃了这方面的功能但是代码忘记改了？

**Comment by peanut996** [comment]
放弃了这个功能。 因为后面发现常见端口号就那么几个。 扫太多时间要很久

**Comment by peanut996** [comment]
已经删除。
