### ISSUE TITLE
能对优选的节点测速吗

### ISSUE THREAD

**Issue by XG-China** [peanut996/CloudflareWarpSpeedTest#4]
大佬这个可以对线路进行测速吗，感觉优选出来的ip有些速度很不理想，还有那个ip在哪里获得的

**Comment by peanut996** [comment]
cloudflare 官方文档有记录warp的ip cidr

目前测速方式只能找到美国机房的warp节点 其实速度基本上差距不大 与你个人使用的工具有关

正在考虑实现香港机房节点的warp测速，香港机房节点速度会很快，但是需要点时间
