### ISSUE TITLE
直接闪退

### ISSUE THREAD

**Issue by deyangyvtian** [peanut996/CloudflareWarpSpeedTest#5]
经常出现
[Info] The total number of IP addresses in the complete speed test results is 0, so skipping the output.
available数量很多
是哪个参数出问题呢

**Comment by peanut996** [comment]
截个图看下呢。能提供你使用的网络环境吗？ 比如ip位置还有就是使用机器

**Comment by peanut996** [comment]
猜想是不是因为你把过滤条件拉的太大了，你不带任何参数试一下呢

**Comment by deyangyvtian** [comment]
![image](https://github.com/peanut996/CloudflareWarpSpeedTest/assets/60131840/fa627838-cc82-4f42-9004-266fa12fb86b)
如图不带任何参数结果也是这样
我使用的是window11，用联通的宽带，和手机移动的流量都是这样

**Comment by peanut996** [comment]
> ![image](https://private-user-images.githubusercontent.com/60131840/293458347-fa627838-cc82-4f42-9004-266fa12fb86b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5Mzc2NDUsIm5iZiI6MTcwMzkzNzM0NSwicGF0aCI6Ii82MDEzMTg0MC8yOTM0NTgzNDctZmE2Mjc4MzgtY2M4Mi00ZjQyLTkwMDQtMjY2ZmExMmZiODZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDExNTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOWZjNzJjMzQ0NWM1MDA3MDQ2ZDkwZWUxZGE0MWVlNmRjMWM5YTM5M2JmZDJiNTYxYmJkOTAyYWNjYmFiNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PeemPbPgTbvr5P5lLprlLQRCObFCBeGso4JI0u8iEhE) 如图不带任何参数结果也是这样 我使用的是window11，用联通的宽带，和手机移动的流量都是这样

加个-v看下版本呢

**Comment by peanut996** [comment]
> ![image](https://private-user-images.githubusercontent.com/60131840/293458347-fa627838-cc82-4f42-9004-266fa12fb86b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5Mzc5MDUsIm5iZiI6MTcwMzkzNzYwNSwicGF0aCI6Ii82MDEzMTg0MC8yOTM0NTgzNDctZmE2Mjc4MzgtY2M4Mi00ZjQyLTkwMDQtMjY2ZmExMmZiODZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDEyMDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNTM1MGMxOTFmNTAxZjVhZTBkZDNhOWM0NGJlMmY2YjIzNTFjNjZjMDY0YWY2MGU4NzZjZjA2NjNmYzc5MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-uwcs0sJFA_ZTQ-06GxX5AMP9R2AOWJITe7fRm0VS1M) 如图不带任何参数结果也是这样 我使用的是window11，用联通的宽带，和手机移动的流量都是这样

把延迟过滤调大一点试试 `-tl 1000`

**Comment by deyangyvtian** [comment]
但是使用cloud flare ST的时候没有出现上述问题

**Comment by peanut996** [comment]
> 但是使用cloud flare ST的时候没有出现上述问题

可以用了嘛？

**Comment by peanut996** [comment]
> 但是使用cloud flare ST的时候没有出现上述问题

是你的网络环境的问题，你ping warp的网速都在300ms以上，所以全部被过滤了。

warp的接入点和普通的cdn不是一个东西

**Comment by deyangyvtian** [comment]
发现只要-t 参数大于20就出现该问题

**Comment by peanut996** [comment]
> 发现只要-t 参数大于30就出现该问题 用的是1.3.2

应该是你的路由器性能太弱了，测速的时候用网应该也快
