### ISSUE TITLE
增加指定端口功能

### ISSUE THREAD

**Issue by PowerfulRichard** [peanut996/CloudflareWarpSpeedTest#7]
当前程序会测试给定ip的所有端口，不是很有必要，一般来说同一ip的不同端口速度不会有太大区别，希望可以增加只测试特定端口的功能
例如：`./CloudflareWarpSpeedTest -f ip.txt -pt port.txt`或是`./CloudflareWarpSpeedTest -ip 1.1.1.1 -port 2408`这样

---

另外，`-full`功能可能有bug，当我使用`.\CloudflareWarpSpeedTest.exe -p 0 -f ip.txt -tlr 0 -o ipv6.csv`测试的时候会显示ip列表的所有ip测试结果，而当加上`-full`参数`.\CloudflareWarpSpeedTest.exe -p 0 -f ip.txt -tlr 0 -o ipv6.csv -full`时候，测试结果只会显示几条

| **不加`-full`** |![image](https://github.com/peanut996/CloudflareWarpSpeedTest/assets/36656969/15e2338b-c81c-4741-8869-5acc9b8f3160)|
|:-------------:|:---:|
| **加`-full`**  |![image](https://github.com/peanut996/CloudflareWarpSpeedTest/assets/36656969/0a2c258e-b4de-4da7-8724-534dd154a463)|

**Comment by peanut996** [comment]
指定输入文件的话，就不会扫描全部ip了，以你给的文件为准，相当于无视`-full`。

如果都知道哪个端口运行了WARP服务的话，这个工具其实用处就不大了。唯一可以做的改动就是如果某个ip的某个port已经成功，那么就不继续扫描了。可以做，但是价值不大.

**Comment by peanut996** [comment]
不过欢迎PR

**Comment by zhuyong96** [comment]
请问你是如何知道warp优选IP开放了哪些端口？

**Comment by peanut996** [comment]
> 请问你是如何知道warp优选IP开放了哪些端口？

官方文档有记录的，但是实际测下来以后发现不止是官方文档提供的那三个端口

https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/firewall/#warp-ingress-ip

**Comment by PowerfulRichard** [comment]
> 如果都知道哪个端口运行了WARP服务的话，这个工具其实用处就不大了。

我这边电信会随机封锁ip的udp连接，对我来说这个工具可以测试warp ipv6地址池中随机ip可用性，然后同步到ddns中，wg配置文件endpoint填ddns域名地址，这样不用每次输ip

**Comment by peanut996** [comment]
> > 如果都知道哪个端口运行了WARP服务的话，这个工具其实用处就不大了。
> 
> 我这边电信会随机封锁ip的udp连接，对我来说这个工具可以测试warp ipv6地址池中随机ip可用性和延迟，然后同步最优地址到ddns中，wg配置文件endpoint填ddns域名地址，这样不用每次输ip

可以的，不过这个工具的IPv6 只是选择了很少的一部分IP进行测试，主打一个“能用就行”

**Comment by PowerfulRichard** [comment]
> IPv6 只是选择了很少的一部分IP进行测试

我的[脚本里带了](https://github.com/PowerfulRichard/CloudflareWarpSpeedTest-DDNS/blob/master/ddns.py)里带了IPv6生成功能
![image](https://github.com/peanut996/CloudflareWarpSpeedTest/assets/36656969/25c687b7-3bc7-433b-90da-02b512638dd8)


> 主打一个“能用就行”

v4地址现在封的比较严重了，实测v6地址嘎嘎快，而且很多，封了就换一个

**Comment by PowerfulRichard** [comment]
> 请问你是如何知道warp优选IP开放了哪些端口？

拿nmap扫，除了官方给的那几个端口，800，900这段还有不少可用端口

**Comment by peanut996** [comment]
> > 请问你是如何知道warp优选IP开放了哪些端口？
> 
> 拿nmap扫，除了官方给的那几个端口，800，900这段还有不少可用端口

扫不动的吧，udp没响应。 wireguard会把不符合的包直接丢掉。 难不成用 TCP 扫？

**Comment by PowerfulRichard** [comment]
> 扫不动的吧，udp没响应。

能扫，但只能扫一点点。可以扫描开放的端口，大部分端口是filtered，但是还有不少是opened，虽然这些端口检测不到wg服务，但是大概率用这些端口能连上，可能是未使用端口自动转发给wg服务了？扫多了会被拉黑，大概隔几百个端口就得换个ip。

**Comment by Misaka-blog** [comment]
> > 请问你是如何知道warp优选IP开放了哪些端口？
> 
> 官方文档有记录的，但是实际测下来以后发现不止是官方文档提供的那三个端口
> 
> https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/firewall/#warp-ingress-ip

https://blog.misaka.rest/2023/01/25/wireguard-warp/?highlight=wireguard

我这里有所有的端口记录
