### ISSUE TITLE
无法生成excel文件

### ISSUE THREAD

**Issue by huanghaobaobao** [peanut996/CloudflareWarpSpeedTest#8]
请问我在下载windows-amd64的release文件后，以管理员身份允行，跑完1000个IP后为什么无法生成相应Excel文件，请问该如何使用？

**Comment by peanut996** [comment]
不会生成excel文件 只会生成result.csv文件

**Comment by huanghaobaobao** [comment]
可是我桌面啥也没有，这是怎么回事？

**Comment by peanut996** [comment]
他不会默认生成在桌面，会默认在你的运行目录里。

**Comment by huanghaobaobao** [comment]
别人的演示视频，运行后会自动生成文件，而我运行完了程序自动退出就啥也没有了

**Comment by peanut996** [comment]
你为什么不在cmd / terminal运行呢

**Comment by huanghaobaobao** [comment]
> 他不会默认生成在桌面，会默认在你的运行目录里。

我把程序放在桌面和桌面新建文件夹中都试了，无文件生成

**Comment by huanghaobaobao** [comment]
> 你为什么不在cmd / terminal运行呢

好的，我再试试，感谢提供这么好的工具

**Comment by peanut996** [comment]
请在terminal/cmd执行， 查看日志输出并丢上来。
